{{- range $index, $service := .Values.services }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
  - name: {{ $service.name }}
    protocol: TCP
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  type: {{ $service.type }}
{{- end -}}