apiVersion: v1
items:
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2018-09-14T08:53:53Z
    name: consumer
    namespace: default
    resourceVersion: "855870"
    selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/consumer
    uid: b521e799-b7fb-11e8-a185-0a58ac1f119d
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: consumer
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""